---
fixtures:
  repositories:
    apt: https://github.com/puppetlabs/puppetlabs-apt.git
    archive: https://github.com/voxpupuli/puppet-archive.git
    augeas_core: https://github.com/puppetlabs/puppetlabs-augeas_core.git
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    systemd: https://github.com/voxpupuli/puppet-systemd.git
    yum: https://github.com/voxpupuli/puppet-yum.git
